function [fitresult, gof] = createFit(wl1, n1)
%CREATEFIT(WL1,N1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: wl1
%      Y Output: n1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Jul-2024 14:54:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( wl1, n1 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'n1 vs. wl1', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'wl1', 'Interpreter', 'none' );
ylabel( 'n1', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'wl1', 'Interpreter', 'none' );
ylabel( 'n1', 'Interpreter', 'none' );
grid on


